### ISSUE TITLE
problems mapping boolean values

### ISSUE THREAD

**Issue by mattetti** [eaigner/jet#4]
Using MySQL I wasn't able to map a tinyint to a go boolean type.

I would like to be able to do that:

``` go
type Project struct {
    Id          int
    Name     string
    Public     bool
    Active     bool
}

var project Project
_ := Db.Query(`select * from projects WHERE id = ? limit 1`, id).Rows(&project)
```

**Comment by mattetti** [comment]
I'm afraid that commit didn't quite work for me:

```
--- FAIL: TestCreateProject (0.03 seconds)
panic: reflect.Value.Convert: value of type int64 cannot be converted to type bool [recovered]
    panic: reflect.Value.Convert: value of type int64 cannot be converted to type bool

goroutine 5 [running]:
testing.func·004()
    /usr/local/Cellar/go/1.1.1/src/pkg/testing/testing.go:348 +0xcd
reflect.Value.Convert(0x1a6560, 0x0, 0x60, 0xc2000b1000, 0x1a59c0, ...)
    /usr/local/Cellar/go/1.1.1/src/pkg/reflect/value.go:2143 +0x1ad
github.com/eaigner/jet.convertAndSet(0x1a6560, 0x0, 0x1a59c0, 0xc200081e00, 0x16, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:99 +0xbd
github.com/eaigner/jet.setValue(0x1a4f40, 0xc2000e5060, 0x146, 0x1a59c0, 0xc200081e00, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:124 +0x6c8
github.com/eaigner/jet.(*mapper).unpackSimple(0xc20007cfe0, 0x0, 0x0, 0x0, 0xc2000e4280, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:92 +0x14f
github.com/eaigner/jet.(*mapper).unpackValue(0xc20007cfe0, 0x0, 0x0, 0x0, 0xc2000e4280, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:44 +0x313
github.com/eaigner/jet.(*mapper).unpackStruct(0xc20007cfe0, 0xc2000e4000, 0xb, 0xb, 0xc2000e4210, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:66 +0x232
github.com/eaigner/jet.(*mapper).unpackValue(0xc20007cfe0, 0xc2000e4000, 0xb, 0xb, 0xc2000e4210, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:36 +0x42b
github.com/eaigner/jet.(*mapper).unpackValue(0xc20007cfe0, 0xc2000e4000, 0xb, 0xb, 0xc2000e4210, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:28 +0x2bf
github.com/eaigner/jet.(*mapper).unpack(0xc20007cfe0, 0xc2000e4000, 0xb, 0xb, 0xc2000e4210, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:19 +0x200
github.com/eaigner/jet.(*runner).Rows(0xc2000813c0, 0x2085a0, 0xc200081dc0, 0x0, 0x0, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/runner.go:125 +0x54b
```

I'm using this MySQL driver: https://github.com/go-sql-driver/mysql and it looks like the mapper might need more manual work to convert a tinyint -> int64 of range 0,1 to true/false.

**Comment by mattetti** [comment]
@eaigner could you reopen this issue please?

**Comment by eaigner** [comment]
I currently don't have time to fix this, but you can send me a pull request. It's actually very simple. 

Add the necessary conversion to the mapper in [`setValue`](https://github.com/eaigner/jet/blob/master/mapper.go#L105), implement the necessary `mapper_test`'s to verify it and send me a pull request.

**Comment by eaigner** [comment]
Furthermore the MySQL driver seems a little fishy to me anyway. Doesn't seem to use correct types in many cases.

**Comment by eaigner** [comment]
Ok, I need to fix some other minor issue today anyway, I think I'll add this too real quick.

**Comment by mattetti** [comment]
Sorry it took so long, but your patch does fix the bool conversion. Thanks!
